package com.caij.emore.database.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "IMAGE_INFO".
 */
public class ImageInfo {

    private String url;
    private Integer width;
    private Integer height;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ImageInfo() {
    }

    public ImageInfo(String url) {
        this.url = url;
    }

    public ImageInfo(String url, Integer width, Integer height) {
        this.url = url;
        this.width = width;
        this.height = height;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
