package com.caij.emore.database.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LIKE_BEAN".
 */
public class LikeBean {

    private Long id;
    private Boolean isLike;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LikeBean() {
    }

    public LikeBean(Long id) {
        this.id = id;
    }

    public LikeBean(Long id, Boolean isLike) {
        this.id = id;
        this.isLike = isLike;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsLike() {
        return isLike;
    }

    public void setIsLike(Boolean isLike) {
        this.isLike = isLike;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
