package com.caij.emore.database.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LONG_TEXT".
 */
public class LongText {

    private Long weiboId;
    private String content;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LongText() {
    }

    public LongText(Long weiboId) {
        this.weiboId = weiboId;
    }


    public Long getWeiboId() {
        return weiboId;
    }

    public void setWeiboId(Long weiboId) {
        this.weiboId = weiboId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
