package com.caij.emore.database.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LONG_TEXT".
 */
public class LongText {

    private Long weiboId;
    private String longTextContent;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LongText() {
    }

    public LongText(Long weiboId) {
        this.weiboId = weiboId;
    }

    public LongText(Long weiboId, String longTextContent) {
        this.weiboId = weiboId;
        this.longTextContent = longTextContent;
    }

    public Long getWeiboId() {
        return weiboId;
    }

    public void setWeiboId(Long weiboId) {
        this.weiboId = weiboId;
    }

    public String getLongTextContent() {
        return longTextContent;
    }

    public void setLongTextContent(String longTextContent) {
        this.longTextContent = longTextContent;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
