package com.caij.emore.database.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table "MESSAGE_IMAGE".
 */
public class MessageImage implements Serializable {

    private Long fid;
    private Long vfid;
    private Long tovfid;
    private String thumbnail_60;
    private String thumbnail_100;
    private String thumbnail_120;
    private String thumbnail_240;
    private String thumbnail_600;
    private Integer http_code;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MessageImage() {
    }

    public MessageImage(Long fid) {
        this.fid = fid;
    }

    public MessageImage(Long fid, Long vfid, Long tovfid, String thumbnail_60, String thumbnail_100, String thumbnail_120, String thumbnail_240, String thumbnail_600, Integer http_code) {
        this.fid = fid;
        this.vfid = vfid;
        this.tovfid = tovfid;
        this.thumbnail_60 = thumbnail_60;
        this.thumbnail_100 = thumbnail_100;
        this.thumbnail_120 = thumbnail_120;
        this.thumbnail_240 = thumbnail_240;
        this.thumbnail_600 = thumbnail_600;
        this.http_code = http_code;
    }

    public Long getFid() {
        return fid;
    }

    public void setFid(Long fid) {
        this.fid = fid;
    }

    public Long getVfid() {
        return vfid;
    }

    public void setVfid(Long vfid) {
        this.vfid = vfid;
    }

    public Long getTovfid() {
        return tovfid;
    }

    public void setTovfid(Long tovfid) {
        this.tovfid = tovfid;
    }

    public String getThumbnail_60() {
        return thumbnail_60;
    }

    public void setThumbnail_60(String thumbnail_60) {
        this.thumbnail_60 = thumbnail_60;
    }

    public String getThumbnail_100() {
        return thumbnail_100;
    }

    public void setThumbnail_100(String thumbnail_100) {
        this.thumbnail_100 = thumbnail_100;
    }

    public String getThumbnail_120() {
        return thumbnail_120;
    }

    public void setThumbnail_120(String thumbnail_120) {
        this.thumbnail_120 = thumbnail_120;
    }

    public String getThumbnail_240() {
        return thumbnail_240;
    }

    public void setThumbnail_240(String thumbnail_240) {
        this.thumbnail_240 = thumbnail_240;
    }

    public String getThumbnail_600() {
        return thumbnail_600;
    }

    public void setThumbnail_600(String thumbnail_600) {
        this.thumbnail_600 = thumbnail_600;
    }

    public Integer getHttp_code() {
        return http_code;
    }

    public void setHttp_code(Integer http_code) {
        this.http_code = http_code;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
