package com.caij.emore.database.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PIC_URL".
 */
public class PicUrl {

    private String id;
    private String thumbnail_pic;
    private Long weibo_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PicUrl() {
    }

    public PicUrl(String id) {
        this.id = id;
    }

    public PicUrl(String id, String thumbnail_pic, Long weibo_id) {
        this.id = id;
        this.thumbnail_pic = thumbnail_pic;
        this.weibo_id = weibo_id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getThumbnail_pic() {
        return thumbnail_pic;
    }

    public void setThumbnail_pic(String thumbnail_pic) {
        this.thumbnail_pic = thumbnail_pic;
    }

    public Long getWeibo_id() {
        return weibo_id;
    }

    public void setWeibo_id(Long weibo_id) {
        this.weibo_id = weibo_id;
    }

//     KEEP METHODS - put your custom methods here
//     KEEP METHODS END

    private int width = -1;

    private int height = -1;

    private String original_pic;

    private String bmiddle_pic;

    public int getWidth() {
        return width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public boolean hasSize() {
        return width > 0 && height > 0;
    }

    public String getOriginal_pic() {
        if (original_pic == null) {
            original_pic = new String(thumbnail_pic).replace("thumbnail", "large");
        }
        return original_pic;
    }

    public String getBmiddle_pic() {
        if (bmiddle_pic == null) {
            bmiddle_pic = new String(thumbnail_pic).replace("thumbnail", "bmiddle");
        }

        return bmiddle_pic;
    }

    public boolean isBigImage() {
        return this.getWidth() / this.getHeight() > 3 || this.getHeight() / this.getWidth() > 3;
    }

    public boolean isBigImageAndHeightBtWidth() {
        return this.getHeight() / this.getWidth() > 3;
    }

}
