package com.caij.emore.database.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "UPLOAD_IMAGE_RESPONSE".
 */
public class UploadImageResponse {

    private String pic_id;
    private String thumbnail_pic;
    private String imagePath;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UploadImageResponse() {
    }

    public UploadImageResponse(String pic_id) {
        this.pic_id = pic_id;
    }

    public UploadImageResponse(String pic_id, String thumbnail_pic, String imagePath) {
        this.pic_id = pic_id;
        this.thumbnail_pic = thumbnail_pic;
        this.imagePath = imagePath;
    }

    public String getPic_id() {
        return pic_id;
    }

    public void setPic_id(String pic_id) {
        this.pic_id = pic_id;
    }

    public String getThumbnail_pic() {
        return thumbnail_pic;
    }

    public void setThumbnail_pic(String thumbnail_pic) {
        this.thumbnail_pic = thumbnail_pic;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
