package com.caij.emore.database.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table "VISIBLE".
 */
public class Visible implements Serializable {

    private String id;
    private String type;
    private String list_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Visible() {
    }

    public Visible(String id) {
        this.id = id;
    }

    public Visible(String id, String type, String list_id) {
        this.id = id;
        this.type = type;
        this.list_id = list_id;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getList_id() {
        return list_id;
    }

    public void setList_id(String list_id) {
        this.list_id = list_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
