package com.caij.emore.database.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.text.Spanned;

import com.caij.emore.bean.PageInfo;
import com.caij.emore.bean.ShortUrl;
import com.caij.emore.bean.response.Response;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import com.caij.emore.bean.ImageInfo;

/**
 * Entity mapped to table "WEIBO".
 */
public class Weibo extends Response implements Serializable {

    private java.util.Date created_at;
    private Long id;
    private Long mid;
    private String idstr;
    private String text;
    private String source;
    private Boolean favorited;
    private Boolean truncated;
    private String in_reply_to_status_id;
    private String in_reply_to_user_id;
    private String in_reply_to_screen_name;
    private String thumbnail_pic;
    private String bmiddle_pic;
    private String original_pic;
    private Integer reposts_count;
    private Integer comments_count;
    private Integer attitudes_count;
    private Integer mlevel;
    private Long update_time = System.currentTimeMillis();
    private Integer attitudes_status;
    private Boolean isLongText;
    private String geo_json_string;
    private String visible_json_string;
    private String url_struct_json_string;
    private String pic_ids_json_string;
    private String pic_infos_json_string;
    private String long_text_json_string;
    private String page_info_json_string;
    private Long retweeted_status_id;
    private Long user_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Weibo() {
    }

    public Weibo(Long id) {
        this.id = id;
    }

    public Weibo(java.util.Date created_at, Long id, Long mid, String idstr, String text, String source, Boolean favorited, Boolean truncated, String in_reply_to_status_id, String in_reply_to_user_id, String in_reply_to_screen_name, String thumbnail_pic, String bmiddle_pic, String original_pic, Integer reposts_count, Integer comments_count, Integer attitudes_count, Integer mlevel, Long update_time, Integer attitudes_status, Boolean isLongText, String geo_json_string, String visible_json_string, String url_struct_json_string, String pic_ids_json_string, String pic_infos_json_string, String long_text_json_string, String page_info_json_string, Long retweeted_status_id, Long user_id) {
        this.created_at = created_at;
        this.id = id;
        this.mid = mid;
        this.idstr = idstr;
        this.text = text;
        this.source = source;
        this.favorited = favorited;
        this.truncated = truncated;
        this.in_reply_to_status_id = in_reply_to_status_id;
        this.in_reply_to_user_id = in_reply_to_user_id;
        this.in_reply_to_screen_name = in_reply_to_screen_name;
        this.thumbnail_pic = thumbnail_pic;
        this.bmiddle_pic = bmiddle_pic;
        this.original_pic = original_pic;
        this.reposts_count = reposts_count;
        this.comments_count = comments_count;
        this.attitudes_count = attitudes_count;
        this.mlevel = mlevel;
        this.update_time = update_time;
        this.attitudes_status = attitudes_status;
        this.isLongText = isLongText;
        this.geo_json_string = geo_json_string;
        this.visible_json_string = visible_json_string;
        this.url_struct_json_string = url_struct_json_string;
        this.pic_ids_json_string = pic_ids_json_string;
        this.pic_infos_json_string = pic_infos_json_string;
        this.long_text_json_string = long_text_json_string;
        this.page_info_json_string = page_info_json_string;
        this.retweeted_status_id = retweeted_status_id;
        this.user_id = user_id;
    }

    public java.util.Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMid() {
        return mid;
    }

    public void setMid(Long mid) {
        this.mid = mid;
    }

    public String getIdstr() {
        return idstr;
    }

    public void setIdstr(String idstr) {
        this.idstr = idstr;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Boolean getFavorited() {
        return favorited;
    }

    public void setFavorited(Boolean favorited) {
        this.favorited = favorited;
    }

    public Boolean getTruncated() {
        return truncated;
    }

    public void setTruncated(Boolean truncated) {
        this.truncated = truncated;
    }

    public String getIn_reply_to_status_id() {
        return in_reply_to_status_id;
    }

    public void setIn_reply_to_status_id(String in_reply_to_status_id) {
        this.in_reply_to_status_id = in_reply_to_status_id;
    }

    public String getIn_reply_to_user_id() {
        return in_reply_to_user_id;
    }

    public void setIn_reply_to_user_id(String in_reply_to_user_id) {
        this.in_reply_to_user_id = in_reply_to_user_id;
    }

    public String getIn_reply_to_screen_name() {
        return in_reply_to_screen_name;
    }

    public void setIn_reply_to_screen_name(String in_reply_to_screen_name) {
        this.in_reply_to_screen_name = in_reply_to_screen_name;
    }

    public String getThumbnail_pic() {
        return thumbnail_pic;
    }

    public void setThumbnail_pic(String thumbnail_pic) {
        this.thumbnail_pic = thumbnail_pic;
    }

    public String getBmiddle_pic() {
        return bmiddle_pic;
    }

    public void setBmiddle_pic(String bmiddle_pic) {
        this.bmiddle_pic = bmiddle_pic;
    }

    public String getOriginal_pic() {
        return original_pic;
    }

    public void setOriginal_pic(String original_pic) {
        this.original_pic = original_pic;
    }

    public Integer getReposts_count() {
        return reposts_count;
    }

    public void setReposts_count(Integer reposts_count) {
        this.reposts_count = reposts_count;
    }

    public Integer getComments_count() {
        return comments_count;
    }

    public void setComments_count(Integer comments_count) {
        this.comments_count = comments_count;
    }

    public Integer getAttitudes_count() {
        return attitudes_count;
    }

    public void setAttitudes_count(Integer attitudes_count) {
        this.attitudes_count = attitudes_count;
    }

    public Integer getMlevel() {
        return mlevel;
    }

    public void setMlevel(Integer mlevel) {
        this.mlevel = mlevel;
    }

    public Long getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }

    public Integer getAttitudes_status() {
        return attitudes_status;
    }

    public void setAttitudes_status(Integer attitudes_status) {
        this.attitudes_status = attitudes_status;
    }

    public Boolean getIsLongText() {
        return isLongText;
    }

    public void setIsLongText(Boolean isLongText) {
        this.isLongText = isLongText;
    }

    public String getGeo_json_string() {
        return geo_json_string;
    }

    public void setGeo_json_string(String geo_json_string) {
        this.geo_json_string = geo_json_string;
    }

    public String getVisible_json_string() {
        return visible_json_string;
    }

    public void setVisible_json_string(String visible_json_string) {
        this.visible_json_string = visible_json_string;
    }

    public String getUrl_struct_json_string() {
        return url_struct_json_string;
    }

    public void setUrl_struct_json_string(String url_struct_json_string) {
        this.url_struct_json_string = url_struct_json_string;
    }

    public String getPic_ids_json_string() {
        return pic_ids_json_string;
    }

    public void setPic_ids_json_string(String pic_ids_json_string) {
        this.pic_ids_json_string = pic_ids_json_string;
    }

    public String getPic_infos_json_string() {
        return pic_infos_json_string;
    }

    public void setPic_infos_json_string(String pic_infos_json_string) {
        this.pic_infos_json_string = pic_infos_json_string;
    }

    public String getLong_text_json_string() {
        return long_text_json_string;
    }

    public void setLong_text_json_string(String long_text_json_string) {
        this.long_text_json_string = long_text_json_string;
    }

    public String getPage_info_json_string() {
        return page_info_json_string;
    }

    public void setPage_info_json_string(String page_info_json_string) {
        this.page_info_json_string = page_info_json_string;
    }

    public Long getRetweeted_status_id() {
        return retweeted_status_id;
    }

    public void setRetweeted_status_id(Long retweeted_status_id) {
        this.retweeted_status_id = retweeted_status_id;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    private Visible visible;
    private LinkedHashMap<String, ImageInfo> pic_infos;
    private Geo geo;
    private User user;
    private Weibo retweeted_status;
    private LongText longText;
    private List<String> pic_ids;
    private List<ShortUrl> url_struct;
    private PageInfo page_info;

    private transient Spanned contentSpannableString;

    public Visible getVisible() {
        return visible;
    }

    public void setVisible(Visible visible) {
        this.visible = visible;
    }

    public LinkedHashMap<String, ImageInfo> getPic_infos() {
        return pic_infos;
    }

    public void setPic_infos(LinkedHashMap<String, ImageInfo> pic_infos) {
        this.pic_infos = pic_infos;
    }

    public Geo getGeo() {
        return geo;
    }

    public void setGeo(Geo geo) {
        this.geo = geo;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Weibo getRetweeted_status() {
        return retweeted_status;
    }

    public void setRetweeted_status(Weibo retweeted_status) {
        this.retweeted_status = retweeted_status;
    }

    public LongText getLongText() {
        return longText;
    }

    public void setLongText(LongText longText) {
        this.longText = longText;
    }

    public List<String> getPic_ids() {
        return pic_ids;
    }

    public void setPic_ids(List<String> pic_ids) {
        this.pic_ids = pic_ids;
    }

    public List<ShortUrl> getUrl_struct() {
        return url_struct;
    }

    public void setUrl_struct(List<ShortUrl> url_struct) {
        this.url_struct = url_struct;
    }

    public Spanned getContentSpannableString() {
        return contentSpannableString;
    }

    public void setContentSpannableString(Spanned contentSpannableString) {
        this.contentSpannableString = contentSpannableString;
    }

    public PageInfo getPage_info() {
        return page_info;
    }

    public void setPage_info(PageInfo page_info) {
        this.page_info = page_info;
    }

    @Override
    public boolean equals(Object o) {
        Weibo  weibo = (Weibo) o;
        return weibo.id.equals(id);
    }


}
