package com.caij.emore.account;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ACCOUNT".
 */
public class Account {

    private Long uid;
    private String username;
    private String pwd;
    private Integer status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Account() {
    }

    public Account(Long uid) {
        this.uid = uid;
    }

    public Account(Long uid, String username, String pwd, Integer status) {
        this.uid = uid;
        this.username = username;
        this.pwd = pwd;
        this.status = status;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public static final int STATUS_USING = 1;
    public static final int STATUS_BACKGROUND = 0;

    private Token emoreToken;
    private Token weiCoToken;

    public Token getEmoreToken() {
        return emoreToken;
    }

    public void setEmoreToken(Token emoreToken) {
        this.emoreToken = emoreToken;
    }

    public Token getWeiCoToken() {
        return weiCoToken;
    }

    public void setWeiCoToken(Token weiCoToken) {
        this.weiCoToken = weiCoToken;
    }

    @Override
    public boolean equals(Object o) {
        Account account = (Account) o;
        return account.uid.equals(uid);
    }
}
