package com.caij.emore.account;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.account.Account;
import com.caij.emore.account.Token;

import com.caij.emore.account.AccountDao;
import com.caij.emore.account.TokenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig tokenDaoConfig;

    private final AccountDao accountDao;
    private final TokenDao tokenDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        tokenDaoConfig = daoConfigMap.get(TokenDao.class).clone();
        tokenDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        tokenDao = new TokenDao(tokenDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Token.class, tokenDao);
    }
    
    public void clear() {
        accountDaoConfig.getIdentityScope().clear();
        tokenDaoConfig.getIdentityScope().clear();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public TokenDao getTokenDao() {
        return tokenDao;
    }

}
