package com.caij.emore.account;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.caij.emore.utils.LogUtil;

import java.util.concurrent.TimeUnit;

/**
 * Entity mapped to table "TOKEN".
 */
public class Token {

    private String uid;
    private String access_token;
    private Long expires_in;
    private Long create_at = System.currentTimeMillis();

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Token() {
    }

    public Token(String uid) {
        this.uid = uid;
    }

    public Token(String uid, String access_token, Long expires_in, Long create_at) {
        this.uid = uid;
        this.access_token = access_token;
        this.expires_in = expires_in;
        this.create_at = create_at;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getAccess_token() {
        return access_token;
    }

    public void setAccess_token(String access_token) {
        this.access_token = access_token;
    }

    public Long getExpires_in() {
        return expires_in;
    }

    public void setExpires_in(Long expires_in) {
        this.expires_in = expires_in;
    }

    public Long getCreate_at() {
        return create_at;
    }

    public void setCreate_at(Long create_at) {
        this.create_at = create_at;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END


    public boolean isExpired() {
        long time  = expires_in * 1000 - (System.currentTimeMillis() - create_at);
        String days = String.valueOf(TimeUnit.MILLISECONDS.toDays(time));
        LogUtil.d(this, "expires_in : %s", expires_in);
        LogUtil.d(this, "%s 还有 %s天失效", uid, days);

        return time <= 0;
    }
}
