package com.caij.emore.account;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TOKEN".
 */
public class Token {

    private String key;
    private Long uid;
    private String access_token;
    private Long expires_in;
    private Long create_at = System.currentTimeMillis();

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Token() {
    }

    public Token(String key) {
        this.key = key;
    }

    public Token(String key, Long uid, String access_token, Long expires_in, Long create_at) {
        this.key = key;
        this.uid = uid;
        this.access_token = access_token;
        this.expires_in = expires_in;
        this.create_at = create_at;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public String getAccess_token() {
        return access_token;
    }

    public void setAccess_token(String access_token) {
        this.access_token = access_token;
    }

    public Long getExpires_in() {
        return expires_in;
    }

    public void setExpires_in(Long expires_in) {
        this.expires_in = expires_in;
    }

    public Long getCreate_at() {
        return create_at;
    }

    public void setCreate_at(Long create_at) {
        this.create_at = create_at;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
