package com.caij.emore.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.database.bean.User;
import com.caij.emore.database.bean.LocakImage;
import com.caij.emore.database.bean.LocalFile;
import com.caij.emore.database.bean.LikeBean;
import com.caij.emore.database.bean.Geo;
import com.caij.emore.database.bean.Weibo;
import com.caij.emore.database.bean.PicUrl;
import com.caij.emore.database.bean.Visible;
import com.caij.emore.database.bean.DirectMessage;
import com.caij.emore.database.bean.MessageImage;
import com.caij.emore.database.bean.UrlInfo;
import com.caij.emore.database.bean.UploadImageResponse;
import com.caij.emore.database.bean.Draft;

import com.caij.emore.database.dao.UserDao;
import com.caij.emore.database.dao.LocakImageDao;
import com.caij.emore.database.dao.LocalFileDao;
import com.caij.emore.database.dao.LikeBeanDao;
import com.caij.emore.database.dao.GeoDao;
import com.caij.emore.database.dao.WeiboDao;
import com.caij.emore.database.dao.PicUrlDao;
import com.caij.emore.database.dao.VisibleDao;
import com.caij.emore.database.dao.DirectMessageDao;
import com.caij.emore.database.dao.MessageImageDao;
import com.caij.emore.database.dao.UrlInfoDao;
import com.caij.emore.database.dao.UploadImageResponseDao;
import com.caij.emore.database.dao.DraftDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig locakImageDaoConfig;
    private final DaoConfig localFileDaoConfig;
    private final DaoConfig likeBeanDaoConfig;
    private final DaoConfig geoDaoConfig;
    private final DaoConfig weiboDaoConfig;
    private final DaoConfig picUrlDaoConfig;
    private final DaoConfig visibleDaoConfig;
    private final DaoConfig directMessageDaoConfig;
    private final DaoConfig messageImageDaoConfig;
    private final DaoConfig urlInfoDaoConfig;
    private final DaoConfig uploadImageResponseDaoConfig;
    private final DaoConfig draftDaoConfig;

    private final UserDao userDao;
    private final LocakImageDao locakImageDao;
    private final LocalFileDao localFileDao;
    private final LikeBeanDao likeBeanDao;
    private final GeoDao geoDao;
    private final WeiboDao weiboDao;
    private final PicUrlDao picUrlDao;
    private final VisibleDao visibleDao;
    private final DirectMessageDao directMessageDao;
    private final MessageImageDao messageImageDao;
    private final UrlInfoDao urlInfoDao;
    private final UploadImageResponseDao uploadImageResponseDao;
    private final DraftDao draftDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        locakImageDaoConfig = daoConfigMap.get(LocakImageDao.class).clone();
        locakImageDaoConfig.initIdentityScope(type);

        localFileDaoConfig = daoConfigMap.get(LocalFileDao.class).clone();
        localFileDaoConfig.initIdentityScope(type);

        likeBeanDaoConfig = daoConfigMap.get(LikeBeanDao.class).clone();
        likeBeanDaoConfig.initIdentityScope(type);

        geoDaoConfig = daoConfigMap.get(GeoDao.class).clone();
        geoDaoConfig.initIdentityScope(type);

        weiboDaoConfig = daoConfigMap.get(WeiboDao.class).clone();
        weiboDaoConfig.initIdentityScope(type);

        picUrlDaoConfig = daoConfigMap.get(PicUrlDao.class).clone();
        picUrlDaoConfig.initIdentityScope(type);

        visibleDaoConfig = daoConfigMap.get(VisibleDao.class).clone();
        visibleDaoConfig.initIdentityScope(type);

        directMessageDaoConfig = daoConfigMap.get(DirectMessageDao.class).clone();
        directMessageDaoConfig.initIdentityScope(type);

        messageImageDaoConfig = daoConfigMap.get(MessageImageDao.class).clone();
        messageImageDaoConfig.initIdentityScope(type);

        urlInfoDaoConfig = daoConfigMap.get(UrlInfoDao.class).clone();
        urlInfoDaoConfig.initIdentityScope(type);

        uploadImageResponseDaoConfig = daoConfigMap.get(UploadImageResponseDao.class).clone();
        uploadImageResponseDaoConfig.initIdentityScope(type);

        draftDaoConfig = daoConfigMap.get(DraftDao.class).clone();
        draftDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        locakImageDao = new LocakImageDao(locakImageDaoConfig, this);
        localFileDao = new LocalFileDao(localFileDaoConfig, this);
        likeBeanDao = new LikeBeanDao(likeBeanDaoConfig, this);
        geoDao = new GeoDao(geoDaoConfig, this);
        weiboDao = new WeiboDao(weiboDaoConfig, this);
        picUrlDao = new PicUrlDao(picUrlDaoConfig, this);
        visibleDao = new VisibleDao(visibleDaoConfig, this);
        directMessageDao = new DirectMessageDao(directMessageDaoConfig, this);
        messageImageDao = new MessageImageDao(messageImageDaoConfig, this);
        urlInfoDao = new UrlInfoDao(urlInfoDaoConfig, this);
        uploadImageResponseDao = new UploadImageResponseDao(uploadImageResponseDaoConfig, this);
        draftDao = new DraftDao(draftDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(LocakImage.class, locakImageDao);
        registerDao(LocalFile.class, localFileDao);
        registerDao(LikeBean.class, likeBeanDao);
        registerDao(Geo.class, geoDao);
        registerDao(Weibo.class, weiboDao);
        registerDao(PicUrl.class, picUrlDao);
        registerDao(Visible.class, visibleDao);
        registerDao(DirectMessage.class, directMessageDao);
        registerDao(MessageImage.class, messageImageDao);
        registerDao(UrlInfo.class, urlInfoDao);
        registerDao(UploadImageResponse.class, uploadImageResponseDao);
        registerDao(Draft.class, draftDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        locakImageDaoConfig.getIdentityScope().clear();
        localFileDaoConfig.getIdentityScope().clear();
        likeBeanDaoConfig.getIdentityScope().clear();
        geoDaoConfig.getIdentityScope().clear();
        weiboDaoConfig.getIdentityScope().clear();
        picUrlDaoConfig.getIdentityScope().clear();
        visibleDaoConfig.getIdentityScope().clear();
        directMessageDaoConfig.getIdentityScope().clear();
        messageImageDaoConfig.getIdentityScope().clear();
        urlInfoDaoConfig.getIdentityScope().clear();
        uploadImageResponseDaoConfig.getIdentityScope().clear();
        draftDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LocakImageDao getLocakImageDao() {
        return locakImageDao;
    }

    public LocalFileDao getLocalFileDao() {
        return localFileDao;
    }

    public LikeBeanDao getLikeBeanDao() {
        return likeBeanDao;
    }

    public GeoDao getGeoDao() {
        return geoDao;
    }

    public WeiboDao getWeiboDao() {
        return weiboDao;
    }

    public PicUrlDao getPicUrlDao() {
        return picUrlDao;
    }

    public VisibleDao getVisibleDao() {
        return visibleDao;
    }

    public DirectMessageDao getDirectMessageDao() {
        return directMessageDao;
    }

    public MessageImageDao getMessageImageDao() {
        return messageImageDao;
    }

    public UrlInfoDao getUrlInfoDao() {
        return urlInfoDao;
    }

    public UploadImageResponseDao getUploadImageResponseDao() {
        return uploadImageResponseDao;
    }

    public DraftDao getDraftDao() {
        return draftDao;
    }

}
