package com.caij.emore.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.database.bean.User;
import com.caij.emore.database.bean.LocalFile;
import com.caij.emore.database.bean.Status;
import com.caij.emore.database.bean.DirectMessage;
import com.caij.emore.database.bean.MessageImage;
import com.caij.emore.database.bean.UrlInfo;
import com.caij.emore.database.bean.UploadImageResponse;
import com.caij.emore.database.bean.Draft;
import com.caij.emore.database.bean.UnReadMessage;

import com.caij.emore.database.dao.UserDao;
import com.caij.emore.database.dao.LocalFileDao;
import com.caij.emore.database.dao.StatusDao;
import com.caij.emore.database.dao.DirectMessageDao;
import com.caij.emore.database.dao.MessageImageDao;
import com.caij.emore.database.dao.UrlInfoDao;
import com.caij.emore.database.dao.UploadImageResponseDao;
import com.caij.emore.database.dao.DraftDao;
import com.caij.emore.database.dao.UnReadMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig localFileDaoConfig;
    private final DaoConfig statusDaoConfig;
    private final DaoConfig directMessageDaoConfig;
    private final DaoConfig messageImageDaoConfig;
    private final DaoConfig urlInfoDaoConfig;
    private final DaoConfig uploadImageResponseDaoConfig;
    private final DaoConfig draftDaoConfig;
    private final DaoConfig unReadMessageDaoConfig;

    private final UserDao userDao;
    private final LocalFileDao localFileDao;
    private final StatusDao statusDao;
    private final DirectMessageDao directMessageDao;
    private final MessageImageDao messageImageDao;
    private final UrlInfoDao urlInfoDao;
    private final UploadImageResponseDao uploadImageResponseDao;
    private final DraftDao draftDao;
    private final UnReadMessageDao unReadMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        localFileDaoConfig = daoConfigMap.get(LocalFileDao.class).clone();
        localFileDaoConfig.initIdentityScope(type);

        statusDaoConfig = daoConfigMap.get(StatusDao.class).clone();
        statusDaoConfig.initIdentityScope(type);

        directMessageDaoConfig = daoConfigMap.get(DirectMessageDao.class).clone();
        directMessageDaoConfig.initIdentityScope(type);

        messageImageDaoConfig = daoConfigMap.get(MessageImageDao.class).clone();
        messageImageDaoConfig.initIdentityScope(type);

        urlInfoDaoConfig = daoConfigMap.get(UrlInfoDao.class).clone();
        urlInfoDaoConfig.initIdentityScope(type);

        uploadImageResponseDaoConfig = daoConfigMap.get(UploadImageResponseDao.class).clone();
        uploadImageResponseDaoConfig.initIdentityScope(type);

        draftDaoConfig = daoConfigMap.get(DraftDao.class).clone();
        draftDaoConfig.initIdentityScope(type);

        unReadMessageDaoConfig = daoConfigMap.get(UnReadMessageDao.class).clone();
        unReadMessageDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        localFileDao = new LocalFileDao(localFileDaoConfig, this);
        statusDao = new StatusDao(statusDaoConfig, this);
        directMessageDao = new DirectMessageDao(directMessageDaoConfig, this);
        messageImageDao = new MessageImageDao(messageImageDaoConfig, this);
        urlInfoDao = new UrlInfoDao(urlInfoDaoConfig, this);
        uploadImageResponseDao = new UploadImageResponseDao(uploadImageResponseDaoConfig, this);
        draftDao = new DraftDao(draftDaoConfig, this);
        unReadMessageDao = new UnReadMessageDao(unReadMessageDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(LocalFile.class, localFileDao);
        registerDao(Status.class, statusDao);
        registerDao(DirectMessage.class, directMessageDao);
        registerDao(MessageImage.class, messageImageDao);
        registerDao(UrlInfo.class, urlInfoDao);
        registerDao(UploadImageResponse.class, uploadImageResponseDao);
        registerDao(Draft.class, draftDao);
        registerDao(UnReadMessage.class, unReadMessageDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        localFileDaoConfig.getIdentityScope().clear();
        statusDaoConfig.getIdentityScope().clear();
        directMessageDaoConfig.getIdentityScope().clear();
        messageImageDaoConfig.getIdentityScope().clear();
        urlInfoDaoConfig.getIdentityScope().clear();
        uploadImageResponseDaoConfig.getIdentityScope().clear();
        draftDaoConfig.getIdentityScope().clear();
        unReadMessageDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LocalFileDao getLocalFileDao() {
        return localFileDao;
    }

    public StatusDao getStatusDao() {
        return statusDao;
    }

    public DirectMessageDao getDirectMessageDao() {
        return directMessageDao;
    }

    public MessageImageDao getMessageImageDao() {
        return messageImageDao;
    }

    public UrlInfoDao getUrlInfoDao() {
        return urlInfoDao;
    }

    public UploadImageResponseDao getUploadImageResponseDao() {
        return uploadImageResponseDao;
    }

    public DraftDao getDraftDao() {
        return draftDao;
    }

    public UnReadMessageDao getUnReadMessageDao() {
        return unReadMessageDao;
    }

}
