package com.caij.emore.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.database.bean.DirectMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIRECT_MESSAGE".
*/
public class DirectMessageDao extends AbstractDao<DirectMessage, Long> {

    public static final String TABLENAME = "DIRECT_MESSAGE";

    /**
     * Properties of entity DirectMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Idstr = new Property(1, String.class, "idstr", false, "IDSTR");
        public final static Property Created_at = new Property(2, java.util.Date.class, "created_at", false, "CREATED_AT");
        public final static Property Text = new Property(3, String.class, "text", false, "TEXT");
        public final static Property Sys_type = new Property(4, Integer.class, "sys_type", false, "SYS_TYPE");
        public final static Property Msg_status = new Property(5, Integer.class, "msg_status", false, "MSG_STATUS");
        public final static Property Sender_id = new Property(6, Long.class, "sender_id", false, "SENDER_ID");
        public final static Property Recipient_id = new Property(7, Long.class, "recipient_id", false, "RECIPIENT_ID");
        public final static Property Sender_screen_name = new Property(8, String.class, "sender_screen_name", false, "SENDER_SCREEN_NAME");
        public final static Property Recipient_screen_name = new Property(9, String.class, "recipient_screen_name", false, "RECIPIENT_SCREEN_NAME");
        public final static Property Mid = new Property(10, String.class, "mid", false, "MID");
        public final static Property IsLargeDm = new Property(11, Boolean.class, "isLargeDm", false, "IS_LARGE_DM");
        public final static Property Source = new Property(12, String.class, "source", false, "SOURCE");
        public final static Property Status_id = new Property(13, Long.class, "status_id", false, "STATUS_ID");
        public final static Property Dm_type = new Property(14, Integer.class, "dm_type", false, "DM_TYPE");
        public final static Property Media_type = new Property(15, Integer.class, "media_type", false, "MEDIA_TYPE");
        public final static Property Ip = new Property(16, Long.class, "ip", false, "IP");
        public final static Property Burn_time = new Property(17, Long.class, "burn_time", false, "BURN_TIME");
        public final static Property MatchKeyword = new Property(18, Boolean.class, "matchKeyword", false, "MATCH_KEYWORD");
        public final static Property Topublic = new Property(19, Boolean.class, "topublic", false, "TOPUBLIC");
        public final static Property PushToMPS = new Property(20, Boolean.class, "pushToMPS", false, "PUSH_TO_MPS");
        public final static Property OriImageId = new Property(21, Long.class, "oriImageId", false, "ORI_IMAGE_ID");
        public final static Property Geo_id = new Property(22, Long.class, "geo_id", false, "GEO_ID");
        public final static Property Local_status = new Property(23, Integer.class, "local_status", false, "LOCAL_STATUS");
        public final static Property Att_ids_json = new Property(24, String.class, "att_ids_json", false, "ATT_IDS_JSON");
        public final static Property Att_infos_json = new Property(25, String.class, "att_infos_json", false, "ATT_INFOS_JSON");
    };


    public DirectMessageDao(DaoConfig config) {
        super(config);
    }
    
    public DirectMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIRECT_MESSAGE\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IDSTR\" TEXT," + // 1: idstr
                "\"CREATED_AT\" INTEGER," + // 2: created_at
                "\"TEXT\" TEXT," + // 3: text
                "\"SYS_TYPE\" INTEGER," + // 4: sys_type
                "\"MSG_STATUS\" INTEGER," + // 5: msg_status
                "\"SENDER_ID\" INTEGER," + // 6: sender_id
                "\"RECIPIENT_ID\" INTEGER," + // 7: recipient_id
                "\"SENDER_SCREEN_NAME\" TEXT," + // 8: sender_screen_name
                "\"RECIPIENT_SCREEN_NAME\" TEXT," + // 9: recipient_screen_name
                "\"MID\" TEXT," + // 10: mid
                "\"IS_LARGE_DM\" INTEGER," + // 11: isLargeDm
                "\"SOURCE\" TEXT," + // 12: source
                "\"STATUS_ID\" INTEGER," + // 13: status_id
                "\"DM_TYPE\" INTEGER," + // 14: dm_type
                "\"MEDIA_TYPE\" INTEGER," + // 15: media_type
                "\"IP\" INTEGER," + // 16: ip
                "\"BURN_TIME\" INTEGER," + // 17: burn_time
                "\"MATCH_KEYWORD\" INTEGER," + // 18: matchKeyword
                "\"TOPUBLIC\" INTEGER," + // 19: topublic
                "\"PUSH_TO_MPS\" INTEGER," + // 20: pushToMPS
                "\"ORI_IMAGE_ID\" INTEGER," + // 21: oriImageId
                "\"GEO_ID\" INTEGER," + // 22: geo_id
                "\"LOCAL_STATUS\" INTEGER," + // 23: local_status
                "\"ATT_IDS_JSON\" TEXT," + // 24: att_ids_json
                "\"ATT_INFOS_JSON\" TEXT);"); // 25: att_infos_json
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIRECT_MESSAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DirectMessage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String idstr = entity.getIdstr();
        if (idstr != null) {
            stmt.bindString(2, idstr);
        }
 
        java.util.Date created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindLong(3, created_at.getTime());
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(4, text);
        }
 
        Integer sys_type = entity.getSys_type();
        if (sys_type != null) {
            stmt.bindLong(5, sys_type);
        }
 
        Integer msg_status = entity.getMsg_status();
        if (msg_status != null) {
            stmt.bindLong(6, msg_status);
        }
 
        Long sender_id = entity.getSender_id();
        if (sender_id != null) {
            stmt.bindLong(7, sender_id);
        }
 
        Long recipient_id = entity.getRecipient_id();
        if (recipient_id != null) {
            stmt.bindLong(8, recipient_id);
        }
 
        String sender_screen_name = entity.getSender_screen_name();
        if (sender_screen_name != null) {
            stmt.bindString(9, sender_screen_name);
        }
 
        String recipient_screen_name = entity.getRecipient_screen_name();
        if (recipient_screen_name != null) {
            stmt.bindString(10, recipient_screen_name);
        }
 
        String mid = entity.getMid();
        if (mid != null) {
            stmt.bindString(11, mid);
        }
 
        Boolean isLargeDm = entity.getIsLargeDm();
        if (isLargeDm != null) {
            stmt.bindLong(12, isLargeDm ? 1L: 0L);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(13, source);
        }
 
        Long status_id = entity.getStatus_id();
        if (status_id != null) {
            stmt.bindLong(14, status_id);
        }
 
        Integer dm_type = entity.getDm_type();
        if (dm_type != null) {
            stmt.bindLong(15, dm_type);
        }
 
        Integer media_type = entity.getMedia_type();
        if (media_type != null) {
            stmt.bindLong(16, media_type);
        }
 
        Long ip = entity.getIp();
        if (ip != null) {
            stmt.bindLong(17, ip);
        }
 
        Long burn_time = entity.getBurn_time();
        if (burn_time != null) {
            stmt.bindLong(18, burn_time);
        }
 
        Boolean matchKeyword = entity.getMatchKeyword();
        if (matchKeyword != null) {
            stmt.bindLong(19, matchKeyword ? 1L: 0L);
        }
 
        Boolean topublic = entity.getTopublic();
        if (topublic != null) {
            stmt.bindLong(20, topublic ? 1L: 0L);
        }
 
        Boolean pushToMPS = entity.getPushToMPS();
        if (pushToMPS != null) {
            stmt.bindLong(21, pushToMPS ? 1L: 0L);
        }
 
        Long oriImageId = entity.getOriImageId();
        if (oriImageId != null) {
            stmt.bindLong(22, oriImageId);
        }
 
        Long geo_id = entity.getGeo_id();
        if (geo_id != null) {
            stmt.bindLong(23, geo_id);
        }
 
        Integer local_status = entity.getLocal_status();
        if (local_status != null) {
            stmt.bindLong(24, local_status);
        }
 
        String att_ids_json = entity.getAtt_ids_json();
        if (att_ids_json != null) {
            stmt.bindString(25, att_ids_json);
        }
 
        String att_infos_json = entity.getAtt_infos_json();
        if (att_infos_json != null) {
            stmt.bindString(26, att_infos_json);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DirectMessage readEntity(Cursor cursor, int offset) {
        DirectMessage entity = new DirectMessage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // idstr
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // created_at
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // text
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // sys_type
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // msg_status
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // sender_id
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // recipient_id
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // sender_screen_name
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // recipient_screen_name
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // mid
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0, // isLargeDm
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // source
            cursor.isNull(offset + 13) ? null : cursor.getLong(offset + 13), // status_id
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // dm_type
            cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15), // media_type
            cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16), // ip
            cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17), // burn_time
            cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0, // matchKeyword
            cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19) != 0, // topublic
            cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20) != 0, // pushToMPS
            cursor.isNull(offset + 21) ? null : cursor.getLong(offset + 21), // oriImageId
            cursor.isNull(offset + 22) ? null : cursor.getLong(offset + 22), // geo_id
            cursor.isNull(offset + 23) ? null : cursor.getInt(offset + 23), // local_status
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // att_ids_json
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25) // att_infos_json
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DirectMessage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdstr(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreated_at(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setText(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSys_type(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setMsg_status(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setSender_id(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setRecipient_id(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setSender_screen_name(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setRecipient_screen_name(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setMid(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setIsLargeDm(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
        entity.setSource(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setStatus_id(cursor.isNull(offset + 13) ? null : cursor.getLong(offset + 13));
        entity.setDm_type(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setMedia_type(cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15));
        entity.setIp(cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16));
        entity.setBurn_time(cursor.isNull(offset + 17) ? null : cursor.getLong(offset + 17));
        entity.setMatchKeyword(cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0);
        entity.setTopublic(cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19) != 0);
        entity.setPushToMPS(cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20) != 0);
        entity.setOriImageId(cursor.isNull(offset + 21) ? null : cursor.getLong(offset + 21));
        entity.setGeo_id(cursor.isNull(offset + 22) ? null : cursor.getLong(offset + 22));
        entity.setLocal_status(cursor.isNull(offset + 23) ? null : cursor.getInt(offset + 23));
        entity.setAtt_ids_json(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setAtt_infos_json(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DirectMessage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DirectMessage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
