package com.caij.emore.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.database.bean.Group;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP".
*/
public class GroupDao extends AbstractDao<Group, Long> {

    public static final String TABLENAME = "GROUP";

    /**
     * Properties of entity Group.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Created_at = new Property(0, java.util.Date.class, "created_at", false, "CREATED_AT");
        public final static Property Description = new Property(1, String.class, "description", false, "DESCRIPTION");
        public final static Property Id = new Property(2, Long.class, "id", true, "ID");
        public final static Property Idstr = new Property(3, String.class, "idstr", false, "IDSTR");
        public final static Property Like_count = new Property(4, Integer.class, "like_count", false, "LIKE_COUNT");
        public final static Property Member_count = new Property(5, Integer.class, "member_count", false, "MEMBER_COUNT");
        public final static Property Mode = new Property(6, String.class, "mode", false, "MODE");
        public final static Property Name = new Property(7, String.class, "name", false, "NAME");
        public final static Property Profile_image_url = new Property(8, String.class, "profile_image_url", false, "PROFILE_IMAGE_URL");
        public final static Property Sysgroup = new Property(9, Integer.class, "sysgroup", false, "SYSGROUP");
        public final static Property Visible = new Property(10, Integer.class, "visible", false, "VISIBLE");
        public final static Property Uid = new Property(11, Long.class, "uid", false, "UID");
    };


    public GroupDao(DaoConfig config) {
        super(config);
    }
    
    public GroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP\" (" + //
                "\"CREATED_AT\" INTEGER," + // 0: created_at
                "\"DESCRIPTION\" TEXT," + // 1: description
                "\"ID\" INTEGER PRIMARY KEY ," + // 2: id
                "\"IDSTR\" TEXT," + // 3: idstr
                "\"LIKE_COUNT\" INTEGER," + // 4: like_count
                "\"MEMBER_COUNT\" INTEGER," + // 5: member_count
                "\"MODE\" TEXT," + // 6: mode
                "\"NAME\" TEXT," + // 7: name
                "\"PROFILE_IMAGE_URL\" TEXT," + // 8: profile_image_url
                "\"SYSGROUP\" INTEGER," + // 9: sysgroup
                "\"VISIBLE\" INTEGER," + // 10: visible
                "\"UID\" INTEGER);"); // 11: uid
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Group entity) {
        stmt.clearBindings();
 
        java.util.Date created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindLong(1, created_at.getTime());
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(2, description);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(3, id);
        }
 
        String idstr = entity.getIdstr();
        if (idstr != null) {
            stmt.bindString(4, idstr);
        }
 
        Integer like_count = entity.getLike_count();
        if (like_count != null) {
            stmt.bindLong(5, like_count);
        }
 
        Integer member_count = entity.getMember_count();
        if (member_count != null) {
            stmt.bindLong(6, member_count);
        }
 
        String mode = entity.getMode();
        if (mode != null) {
            stmt.bindString(7, mode);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(8, name);
        }
 
        String profile_image_url = entity.getProfile_image_url();
        if (profile_image_url != null) {
            stmt.bindString(9, profile_image_url);
        }
 
        Integer sysgroup = entity.getSysgroup();
        if (sysgroup != null) {
            stmt.bindLong(10, sysgroup);
        }
 
        Integer visible = entity.getVisible();
        if (visible != null) {
            stmt.bindLong(11, visible);
        }
 
        Long uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(12, uid);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2);
    }    

    /** @inheritdoc */
    @Override
    public Group readEntity(Cursor cursor, int offset) {
        Group entity = new Group( //
            cursor.isNull(offset + 0) ? null : new java.util.Date(cursor.getLong(offset + 0)), // created_at
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // description
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // idstr
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // like_count
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // member_count
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // mode
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // name
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // profile_image_url
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // sysgroup
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // visible
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11) // uid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Group entity, int offset) {
        entity.setCreated_at(cursor.isNull(offset + 0) ? null : new java.util.Date(cursor.getLong(offset + 0)));
        entity.setDescription(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIdstr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLike_count(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setMember_count(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setMode(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setProfile_image_url(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSysgroup(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setVisible(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setUid(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Group entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Group entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
