package com.caij.emore.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.database.bean.LongText;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LONG_TEXT".
*/
public class LongTextDao extends AbstractDao<LongText, Long> {

    public static final String TABLENAME = "LONG_TEXT";

    /**
     * Properties of entity LongText.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property WeiboId = new Property(0, Long.class, "weiboId", true, "WEIBO_ID");
        public final static Property LongTextContent = new Property(1, String.class, "longTextContent", false, "LONG_TEXT_CONTENT");
    };


    public LongTextDao(DaoConfig config) {
        super(config);
    }
    
    public LongTextDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LONG_TEXT\" (" + //
                "\"WEIBO_ID\" INTEGER PRIMARY KEY ," + // 0: weiboId
                "\"LONG_TEXT_CONTENT\" TEXT);"); // 1: longTextContent
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LONG_TEXT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LongText entity) {
        stmt.clearBindings();
 
        Long weiboId = entity.getWeiboId();
        if (weiboId != null) {
            stmt.bindLong(1, weiboId);
        }
 
        String longTextContent = entity.getLongTextContent();
        if (longTextContent != null) {
            stmt.bindString(2, longTextContent);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LongText readEntity(Cursor cursor, int offset) {
        LongText entity = new LongText( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // weiboId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // longTextContent
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LongText entity, int offset) {
        entity.setWeiboId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLongTextContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LongText entity, long rowId) {
        entity.setWeiboId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LongText entity) {
        if(entity != null) {
            return entity.getWeiboId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
