package com.caij.emore.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.database.bean.MessageImage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE_IMAGE".
*/
public class MessageImageDao extends AbstractDao<MessageImage, Long> {

    public static final String TABLENAME = "MESSAGE_IMAGE";

    /**
     * Properties of entity MessageImage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Fid = new Property(0, Long.class, "fid", true, "FID");
        public final static Property Vfid = new Property(1, Long.class, "vfid", false, "VFID");
        public final static Property Tovfid = new Property(2, Long.class, "tovfid", false, "TOVFID");
        public final static Property Thumbnail_60 = new Property(3, String.class, "thumbnail_60", false, "THUMBNAIL_60");
        public final static Property Thumbnail_100 = new Property(4, String.class, "thumbnail_100", false, "THUMBNAIL_100");
        public final static Property Thumbnail_120 = new Property(5, String.class, "thumbnail_120", false, "THUMBNAIL_120");
        public final static Property Thumbnail_240 = new Property(6, String.class, "thumbnail_240", false, "THUMBNAIL_240");
        public final static Property Thumbnail_600 = new Property(7, String.class, "thumbnail_600", false, "THUMBNAIL_600");
        public final static Property Http_code = new Property(8, Integer.class, "http_code", false, "HTTP_CODE");
    };


    public MessageImageDao(DaoConfig config) {
        super(config);
    }
    
    public MessageImageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE_IMAGE\" (" + //
                "\"FID\" INTEGER PRIMARY KEY ," + // 0: fid
                "\"VFID\" INTEGER," + // 1: vfid
                "\"TOVFID\" INTEGER," + // 2: tovfid
                "\"THUMBNAIL_60\" TEXT," + // 3: thumbnail_60
                "\"THUMBNAIL_100\" TEXT," + // 4: thumbnail_100
                "\"THUMBNAIL_120\" TEXT," + // 5: thumbnail_120
                "\"THUMBNAIL_240\" TEXT," + // 6: thumbnail_240
                "\"THUMBNAIL_600\" TEXT," + // 7: thumbnail_600
                "\"HTTP_CODE\" INTEGER);"); // 8: http_code
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE_IMAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MessageImage entity) {
        stmt.clearBindings();
 
        Long fid = entity.getFid();
        if (fid != null) {
            stmt.bindLong(1, fid);
        }
 
        Long vfid = entity.getVfid();
        if (vfid != null) {
            stmt.bindLong(2, vfid);
        }
 
        Long tovfid = entity.getTovfid();
        if (tovfid != null) {
            stmt.bindLong(3, tovfid);
        }
 
        String thumbnail_60 = entity.getThumbnail_60();
        if (thumbnail_60 != null) {
            stmt.bindString(4, thumbnail_60);
        }
 
        String thumbnail_100 = entity.getThumbnail_100();
        if (thumbnail_100 != null) {
            stmt.bindString(5, thumbnail_100);
        }
 
        String thumbnail_120 = entity.getThumbnail_120();
        if (thumbnail_120 != null) {
            stmt.bindString(6, thumbnail_120);
        }
 
        String thumbnail_240 = entity.getThumbnail_240();
        if (thumbnail_240 != null) {
            stmt.bindString(7, thumbnail_240);
        }
 
        String thumbnail_600 = entity.getThumbnail_600();
        if (thumbnail_600 != null) {
            stmt.bindString(8, thumbnail_600);
        }
 
        Integer http_code = entity.getHttp_code();
        if (http_code != null) {
            stmt.bindLong(9, http_code);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MessageImage readEntity(Cursor cursor, int offset) {
        MessageImage entity = new MessageImage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // fid
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // vfid
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // tovfid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // thumbnail_60
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // thumbnail_100
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // thumbnail_120
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // thumbnail_240
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // thumbnail_600
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // http_code
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MessageImage entity, int offset) {
        entity.setFid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVfid(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTovfid(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setThumbnail_60(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setThumbnail_100(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setThumbnail_120(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setThumbnail_240(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setThumbnail_600(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setHttp_code(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MessageImage entity, long rowId) {
        entity.setFid(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MessageImage entity) {
        if(entity != null) {
            return entity.getFid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
