package com.caij.emore.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.database.bean.UploadImageResponse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UPLOAD_IMAGE_RESPONSE".
*/
public class UploadImageResponseDao extends AbstractDao<UploadImageResponse, String> {

    public static final String TABLENAME = "UPLOAD_IMAGE_RESPONSE";

    /**
     * Properties of entity UploadImageResponse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Pic_id = new Property(0, String.class, "pic_id", true, "PIC_ID");
        public final static Property Thumbnail_pic = new Property(1, String.class, "thumbnail_pic", false, "THUMBNAIL_PIC");
        public final static Property ImagePath = new Property(2, String.class, "imagePath", false, "IMAGE_PATH");
    };


    public UploadImageResponseDao(DaoConfig config) {
        super(config);
    }
    
    public UploadImageResponseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UPLOAD_IMAGE_RESPONSE\" (" + //
                "\"PIC_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: pic_id
                "\"THUMBNAIL_PIC\" TEXT," + // 1: thumbnail_pic
                "\"IMAGE_PATH\" TEXT);"); // 2: imagePath
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UPLOAD_IMAGE_RESPONSE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UploadImageResponse entity) {
        stmt.clearBindings();
 
        String pic_id = entity.getPic_id();
        if (pic_id != null) {
            stmt.bindString(1, pic_id);
        }
 
        String thumbnail_pic = entity.getThumbnail_pic();
        if (thumbnail_pic != null) {
            stmt.bindString(2, thumbnail_pic);
        }
 
        String imagePath = entity.getImagePath();
        if (imagePath != null) {
            stmt.bindString(3, imagePath);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UploadImageResponse readEntity(Cursor cursor, int offset) {
        UploadImageResponse entity = new UploadImageResponse( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // pic_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // thumbnail_pic
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // imagePath
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UploadImageResponse entity, int offset) {
        entity.setPic_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setThumbnail_pic(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImagePath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(UploadImageResponse entity, long rowId) {
        return entity.getPic_id();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(UploadImageResponse entity) {
        if(entity != null) {
            return entity.getPic_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
