package com.caij.emore.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.database.bean.UrlInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "URL_INFO".
*/
public class UrlInfoDao extends AbstractDao<UrlInfo, String> {

    public static final String TABLENAME = "URL_INFO";

    /**
     * Properties of entity UrlInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ShortUrl = new Property(0, String.class, "shortUrl", true, "SHORT_URL");
        public final static Property LongUrl = new Property(1, String.class, "longUrl", false, "LONG_URL");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property Object_type = new Property(3, String.class, "object_type", false, "OBJECT_TYPE");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property Display_name = new Property(5, String.class, "display_name", false, "DISPLAY_NAME");
        public final static Property Transcode = new Property(6, Integer.class, "transcode", false, "TRANSCODE");
        public final static Property Type = new Property(7, Integer.class, "type", false, "TYPE");
        public final static Property ShortUrlAvailable = new Property(8, Boolean.class, "shortUrlAvailable", false, "SHORT_URL_AVAILABLE");
    };


    public UrlInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UrlInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"URL_INFO\" (" + //
                "\"SHORT_URL\" TEXT PRIMARY KEY NOT NULL ," + // 0: shortUrl
                "\"LONG_URL\" TEXT," + // 1: longUrl
                "\"DESCRIPTION\" TEXT," + // 2: description
                "\"OBJECT_TYPE\" TEXT," + // 3: object_type
                "\"TITLE\" TEXT," + // 4: title
                "\"DISPLAY_NAME\" TEXT," + // 5: display_name
                "\"TRANSCODE\" INTEGER," + // 6: transcode
                "\"TYPE\" INTEGER," + // 7: type
                "\"SHORT_URL_AVAILABLE\" INTEGER);"); // 8: shortUrlAvailable
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"URL_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UrlInfo entity) {
        stmt.clearBindings();
 
        String shortUrl = entity.getShortUrl();
        if (shortUrl != null) {
            stmt.bindString(1, shortUrl);
        }
 
        String longUrl = entity.getLongUrl();
        if (longUrl != null) {
            stmt.bindString(2, longUrl);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
 
        String object_type = entity.getObject_type();
        if (object_type != null) {
            stmt.bindString(4, object_type);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
 
        String display_name = entity.getDisplay_name();
        if (display_name != null) {
            stmt.bindString(6, display_name);
        }
 
        Integer transcode = entity.getTranscode();
        if (transcode != null) {
            stmt.bindLong(7, transcode);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(8, type);
        }
 
        Boolean shortUrlAvailable = entity.getShortUrlAvailable();
        if (shortUrlAvailable != null) {
            stmt.bindLong(9, shortUrlAvailable ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UrlInfo readEntity(Cursor cursor, int offset) {
        UrlInfo entity = new UrlInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // shortUrl
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // longUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // description
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // object_type
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // display_name
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // transcode
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // type
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0 // shortUrlAvailable
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UrlInfo entity, int offset) {
        entity.setShortUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLongUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setObject_type(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDisplay_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTranscode(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setType(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setShortUrlAvailable(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(UrlInfo entity, long rowId) {
        return entity.getShortUrl();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(UrlInfo entity) {
        if(entity != null) {
            return entity.getShortUrl();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
