package com.caij.emore.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.emore.database.bean.Weibo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEIBO".
*/
public class WeiboDao extends AbstractDao<Weibo, Long> {

    public static final String TABLENAME = "WEIBO";

    /**
     * Properties of entity Weibo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Created_at = new Property(0, String.class, "created_at", false, "CREATED_AT");
        public final static Property Id = new Property(1, Long.class, "id", true, "ID");
        public final static Property Mid = new Property(2, Long.class, "mid", false, "MID");
        public final static Property Idstr = new Property(3, String.class, "idstr", false, "IDSTR");
        public final static Property Text = new Property(4, String.class, "text", false, "TEXT");
        public final static Property Source = new Property(5, String.class, "source", false, "SOURCE");
        public final static Property Favorited = new Property(6, Boolean.class, "favorited", false, "FAVORITED");
        public final static Property Truncated = new Property(7, Boolean.class, "truncated", false, "TRUNCATED");
        public final static Property In_reply_to_status_id = new Property(8, String.class, "in_reply_to_status_id", false, "IN_REPLY_TO_STATUS_ID");
        public final static Property In_reply_to_user_id = new Property(9, String.class, "in_reply_to_user_id", false, "IN_REPLY_TO_USER_ID");
        public final static Property In_reply_to_screen_name = new Property(10, String.class, "in_reply_to_screen_name", false, "IN_REPLY_TO_SCREEN_NAME");
        public final static Property Thumbnail_pic = new Property(11, String.class, "thumbnail_pic", false, "THUMBNAIL_PIC");
        public final static Property Bmiddle_pic = new Property(12, String.class, "bmiddle_pic", false, "BMIDDLE_PIC");
        public final static Property Original_pic = new Property(13, String.class, "original_pic", false, "ORIGINAL_PIC");
        public final static Property Reposts_count = new Property(14, Integer.class, "reposts_count", false, "REPOSTS_COUNT");
        public final static Property Comments_count = new Property(15, Integer.class, "comments_count", false, "COMMENTS_COUNT");
        public final static Property Attitudes_count = new Property(16, Integer.class, "attitudes_count", false, "ATTITUDES_COUNT");
        public final static Property Mlevel = new Property(17, Integer.class, "mlevel", false, "MLEVEL");
        public final static Property Update_time = new Property(18, Long.class, "update_time", false, "UPDATE_TIME");
        public final static Property Create_at_long = new Property(19, Long.class, "create_at_long", false, "CREATE_AT_LONG");
        public final static Property IsLongText = new Property(20, Long.class, "isLongText", false, "IS_LONG_TEXT");
        public final static Property Geo_id = new Property(21, String.class, "geo_id", false, "GEO_ID");
        public final static Property User_id = new Property(22, Long.class, "user_id", false, "USER_ID");
        public final static Property Visible_id = new Property(23, String.class, "visible_id", false, "VISIBLE_ID");
        public final static Property Retweeted_status_id = new Property(24, Long.class, "retweeted_status_id", false, "RETWEETED_STATUS_ID");
    };


    public WeiboDao(DaoConfig config) {
        super(config);
    }
    
    public WeiboDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEIBO\" (" + //
                "\"CREATED_AT\" TEXT," + // 0: created_at
                "\"ID\" INTEGER PRIMARY KEY ," + // 1: id
                "\"MID\" INTEGER," + // 2: mid
                "\"IDSTR\" TEXT," + // 3: idstr
                "\"TEXT\" TEXT," + // 4: text
                "\"SOURCE\" TEXT," + // 5: source
                "\"FAVORITED\" INTEGER," + // 6: favorited
                "\"TRUNCATED\" INTEGER," + // 7: truncated
                "\"IN_REPLY_TO_STATUS_ID\" TEXT," + // 8: in_reply_to_status_id
                "\"IN_REPLY_TO_USER_ID\" TEXT," + // 9: in_reply_to_user_id
                "\"IN_REPLY_TO_SCREEN_NAME\" TEXT," + // 10: in_reply_to_screen_name
                "\"THUMBNAIL_PIC\" TEXT," + // 11: thumbnail_pic
                "\"BMIDDLE_PIC\" TEXT," + // 12: bmiddle_pic
                "\"ORIGINAL_PIC\" TEXT," + // 13: original_pic
                "\"REPOSTS_COUNT\" INTEGER," + // 14: reposts_count
                "\"COMMENTS_COUNT\" INTEGER," + // 15: comments_count
                "\"ATTITUDES_COUNT\" INTEGER," + // 16: attitudes_count
                "\"MLEVEL\" INTEGER," + // 17: mlevel
                "\"UPDATE_TIME\" INTEGER," + // 18: update_time
                "\"CREATE_AT_LONG\" INTEGER," + // 19: create_at_long
                "\"IS_LONG_TEXT\" INTEGER," + // 20: isLongText
                "\"GEO_ID\" TEXT," + // 21: geo_id
                "\"USER_ID\" INTEGER," + // 22: user_id
                "\"VISIBLE_ID\" TEXT," + // 23: visible_id
                "\"RETWEETED_STATUS_ID\" INTEGER);"); // 24: retweeted_status_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEIBO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Weibo entity) {
        stmt.clearBindings();
 
        String created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindString(1, created_at);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        Long mid = entity.getMid();
        if (mid != null) {
            stmt.bindLong(3, mid);
        }
 
        String idstr = entity.getIdstr();
        if (idstr != null) {
            stmt.bindString(4, idstr);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(5, text);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(6, source);
        }
 
        Boolean favorited = entity.getFavorited();
        if (favorited != null) {
            stmt.bindLong(7, favorited ? 1L: 0L);
        }
 
        Boolean truncated = entity.getTruncated();
        if (truncated != null) {
            stmt.bindLong(8, truncated ? 1L: 0L);
        }
 
        String in_reply_to_status_id = entity.getIn_reply_to_status_id();
        if (in_reply_to_status_id != null) {
            stmt.bindString(9, in_reply_to_status_id);
        }
 
        String in_reply_to_user_id = entity.getIn_reply_to_user_id();
        if (in_reply_to_user_id != null) {
            stmt.bindString(10, in_reply_to_user_id);
        }
 
        String in_reply_to_screen_name = entity.getIn_reply_to_screen_name();
        if (in_reply_to_screen_name != null) {
            stmt.bindString(11, in_reply_to_screen_name);
        }
 
        String thumbnail_pic = entity.getThumbnail_pic();
        if (thumbnail_pic != null) {
            stmt.bindString(12, thumbnail_pic);
        }
 
        String bmiddle_pic = entity.getBmiddle_pic();
        if (bmiddle_pic != null) {
            stmt.bindString(13, bmiddle_pic);
        }
 
        String original_pic = entity.getOriginal_pic();
        if (original_pic != null) {
            stmt.bindString(14, original_pic);
        }
 
        Integer reposts_count = entity.getReposts_count();
        if (reposts_count != null) {
            stmt.bindLong(15, reposts_count);
        }
 
        Integer comments_count = entity.getComments_count();
        if (comments_count != null) {
            stmt.bindLong(16, comments_count);
        }
 
        Integer attitudes_count = entity.getAttitudes_count();
        if (attitudes_count != null) {
            stmt.bindLong(17, attitudes_count);
        }
 
        Integer mlevel = entity.getMlevel();
        if (mlevel != null) {
            stmt.bindLong(18, mlevel);
        }
 
        Long update_time = entity.getUpdate_time();
        if (update_time != null) {
            stmt.bindLong(19, update_time);
        }
 
        Long create_at_long = entity.getCreate_at_long();
        if (create_at_long != null) {
            stmt.bindLong(20, create_at_long);
        }
 
        Long isLongText = entity.getIsLongText();
        if (isLongText != null) {
            stmt.bindLong(21, isLongText);
        }
 
        String geo_id = entity.getGeo_id();
        if (geo_id != null) {
            stmt.bindString(22, geo_id);
        }
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(23, user_id);
        }
 
        String visible_id = entity.getVisible_id();
        if (visible_id != null) {
            stmt.bindString(24, visible_id);
        }
 
        Long retweeted_status_id = entity.getRetweeted_status_id();
        if (retweeted_status_id != null) {
            stmt.bindLong(25, retweeted_status_id);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public Weibo readEntity(Cursor cursor, int offset) {
        Weibo entity = new Weibo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // created_at
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // mid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // idstr
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // text
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // source
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // favorited
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // truncated
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // in_reply_to_status_id
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // in_reply_to_user_id
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // in_reply_to_screen_name
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // thumbnail_pic
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // bmiddle_pic
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // original_pic
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // reposts_count
            cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15), // comments_count
            cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16), // attitudes_count
            cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17), // mlevel
            cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18), // update_time
            cursor.isNull(offset + 19) ? null : cursor.getLong(offset + 19), // create_at_long
            cursor.isNull(offset + 20) ? null : cursor.getLong(offset + 20), // isLongText
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // geo_id
            cursor.isNull(offset + 22) ? null : cursor.getLong(offset + 22), // user_id
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // visible_id
            cursor.isNull(offset + 24) ? null : cursor.getLong(offset + 24) // retweeted_status_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Weibo entity, int offset) {
        entity.setCreated_at(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMid(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIdstr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setText(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSource(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFavorited(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setTruncated(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setIn_reply_to_status_id(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setIn_reply_to_user_id(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setIn_reply_to_screen_name(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setThumbnail_pic(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setBmiddle_pic(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setOriginal_pic(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setReposts_count(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setComments_count(cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15));
        entity.setAttitudes_count(cursor.isNull(offset + 16) ? null : cursor.getInt(offset + 16));
        entity.setMlevel(cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17));
        entity.setUpdate_time(cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18));
        entity.setCreate_at_long(cursor.isNull(offset + 19) ? null : cursor.getLong(offset + 19));
        entity.setIsLongText(cursor.isNull(offset + 20) ? null : cursor.getLong(offset + 20));
        entity.setGeo_id(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setUser_id(cursor.isNull(offset + 22) ? null : cursor.getLong(offset + 22));
        entity.setVisible_id(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setRetweeted_status_id(cursor.isNull(offset + 24) ? null : cursor.getLong(offset + 24));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Weibo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Weibo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
