package com.caij.emore.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.caij.emore.utils.ImageUtil;

import java.io.Serializable;

/**
 */
public class ImageInfo implements Serializable {

    private String url;
    private Integer width;
    private Integer height;
    private String imageType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ImageInfo() {
    }

    public ImageInfo(String url) {
        this.url = url;
    }

    public ImageInfo(String url, Integer width, Integer height, String imageType) {
        this.url = url;
        this.width = width;
        this.height = height;
        this.imageType = imageType;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public String getImageType() {
        return imageType;
    }

    public void setImageType(String imageType) {
        this.imageType = imageType;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
