package com.caij.weiyo.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.weiyo.database.bean.LocalUser;
import com.caij.weiyo.database.bean.FriendWeibo;
import com.caij.weiyo.database.bean.UserWeibo;
import com.caij.weiyo.database.bean.LocakImage;

import com.caij.weiyo.database.dao.LocalUserDao;
import com.caij.weiyo.database.dao.FriendWeiboDao;
import com.caij.weiyo.database.dao.UserWeiboDao;
import com.caij.weiyo.database.dao.LocakImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localUserDaoConfig;
    private final DaoConfig friendWeiboDaoConfig;
    private final DaoConfig userWeiboDaoConfig;
    private final DaoConfig locakImageDaoConfig;

    private final LocalUserDao localUserDao;
    private final FriendWeiboDao friendWeiboDao;
    private final UserWeiboDao userWeiboDao;
    private final LocakImageDao locakImageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localUserDaoConfig = daoConfigMap.get(LocalUserDao.class).clone();
        localUserDaoConfig.initIdentityScope(type);

        friendWeiboDaoConfig = daoConfigMap.get(FriendWeiboDao.class).clone();
        friendWeiboDaoConfig.initIdentityScope(type);

        userWeiboDaoConfig = daoConfigMap.get(UserWeiboDao.class).clone();
        userWeiboDaoConfig.initIdentityScope(type);

        locakImageDaoConfig = daoConfigMap.get(LocakImageDao.class).clone();
        locakImageDaoConfig.initIdentityScope(type);

        localUserDao = new LocalUserDao(localUserDaoConfig, this);
        friendWeiboDao = new FriendWeiboDao(friendWeiboDaoConfig, this);
        userWeiboDao = new UserWeiboDao(userWeiboDaoConfig, this);
        locakImageDao = new LocakImageDao(locakImageDaoConfig, this);

        registerDao(LocalUser.class, localUserDao);
        registerDao(FriendWeibo.class, friendWeiboDao);
        registerDao(UserWeibo.class, userWeiboDao);
        registerDao(LocakImage.class, locakImageDao);
    }
    
    public void clear() {
        localUserDaoConfig.getIdentityScope().clear();
        friendWeiboDaoConfig.getIdentityScope().clear();
        userWeiboDaoConfig.getIdentityScope().clear();
        locakImageDaoConfig.getIdentityScope().clear();
    }

    public LocalUserDao getLocalUserDao() {
        return localUserDao;
    }

    public FriendWeiboDao getFriendWeiboDao() {
        return friendWeiboDao;
    }

    public UserWeiboDao getUserWeiboDao() {
        return userWeiboDao;
    }

    public LocakImageDao getLocakImageDao() {
        return locakImageDao;
    }

}
