package com.caij.weiyo.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.caij.weiyo.database.bean.UserWeibo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_WEIBO".
*/
public class UserWeiboDao extends AbstractDao<UserWeibo, Long> {

    public static final String TABLENAME = "USER_WEIBO";

    /**
     * Properties of entity UserWeibo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property User_id = new Property(0, Long.class, "user_id", false, "USER_ID");
        public final static Property Created_at = new Property(1, String.class, "created_at", false, "CREATED_AT");
        public final static Property Id = new Property(2, Long.class, "id", true, "ID");
        public final static Property Mid = new Property(3, Long.class, "mid", false, "MID");
        public final static Property Idstr = new Property(4, String.class, "idstr", false, "IDSTR");
        public final static Property Text = new Property(5, String.class, "text", false, "TEXT");
        public final static Property Source = new Property(6, String.class, "source", false, "SOURCE");
        public final static Property Favorited = new Property(7, Boolean.class, "favorited", false, "FAVORITED");
        public final static Property Truncated = new Property(8, Boolean.class, "truncated", false, "TRUNCATED");
        public final static Property In_reply_to_status_id = new Property(9, String.class, "in_reply_to_status_id", false, "IN_REPLY_TO_STATUS_ID");
        public final static Property In_reply_to_user_id = new Property(10, String.class, "in_reply_to_user_id", false, "IN_REPLY_TO_USER_ID");
        public final static Property In_reply_to_screen_name = new Property(11, String.class, "in_reply_to_screen_name", false, "IN_REPLY_TO_SCREEN_NAME");
        public final static Property Thumbnail_pic = new Property(12, String.class, "thumbnail_pic", false, "THUMBNAIL_PIC");
        public final static Property Bmiddle_pic = new Property(13, String.class, "bmiddle_pic", false, "BMIDDLE_PIC");
        public final static Property Original_pic = new Property(14, String.class, "original_pic", false, "ORIGINAL_PIC");
        public final static Property Geo_json = new Property(15, String.class, "geo_json", false, "GEO_JSON");
        public final static Property User_json = new Property(16, String.class, "user_json", false, "USER_JSON");
        public final static Property Retweeted_status_json = new Property(17, String.class, "retweeted_status_json", false, "RETWEETED_STATUS_JSON");
        public final static Property Reposts_count = new Property(18, Integer.class, "reposts_count", false, "REPOSTS_COUNT");
        public final static Property Comments_count = new Property(19, Integer.class, "comments_count", false, "COMMENTS_COUNT");
        public final static Property Attitudes_count = new Property(20, Integer.class, "attitudes_count", false, "ATTITUDES_COUNT");
        public final static Property Mlevel = new Property(21, Integer.class, "mlevel", false, "MLEVEL");
        public final static Property Visible_json = new Property(22, String.class, "visible_json", false, "VISIBLE_JSON");
        public final static Property Pic_ids_json = new Property(23, String.class, "pic_ids_json", false, "PIC_IDS_JSON");
        public final static Property Create_time = new Property(24, Long.class, "create_time", false, "CREATE_TIME");
    };


    public UserWeiboDao(DaoConfig config) {
        super(config);
    }
    
    public UserWeiboDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_WEIBO\" (" + //
                "\"USER_ID\" INTEGER," + // 0: user_id
                "\"CREATED_AT\" TEXT," + // 1: created_at
                "\"ID\" INTEGER PRIMARY KEY ," + // 2: id
                "\"MID\" INTEGER," + // 3: mid
                "\"IDSTR\" TEXT," + // 4: idstr
                "\"TEXT\" TEXT," + // 5: text
                "\"SOURCE\" TEXT," + // 6: source
                "\"FAVORITED\" INTEGER," + // 7: favorited
                "\"TRUNCATED\" INTEGER," + // 8: truncated
                "\"IN_REPLY_TO_STATUS_ID\" TEXT," + // 9: in_reply_to_status_id
                "\"IN_REPLY_TO_USER_ID\" TEXT," + // 10: in_reply_to_user_id
                "\"IN_REPLY_TO_SCREEN_NAME\" TEXT," + // 11: in_reply_to_screen_name
                "\"THUMBNAIL_PIC\" TEXT," + // 12: thumbnail_pic
                "\"BMIDDLE_PIC\" TEXT," + // 13: bmiddle_pic
                "\"ORIGINAL_PIC\" TEXT," + // 14: original_pic
                "\"GEO_JSON\" TEXT," + // 15: geo_json
                "\"USER_JSON\" TEXT," + // 16: user_json
                "\"RETWEETED_STATUS_JSON\" TEXT," + // 17: retweeted_status_json
                "\"REPOSTS_COUNT\" INTEGER," + // 18: reposts_count
                "\"COMMENTS_COUNT\" INTEGER," + // 19: comments_count
                "\"ATTITUDES_COUNT\" INTEGER," + // 20: attitudes_count
                "\"MLEVEL\" INTEGER," + // 21: mlevel
                "\"VISIBLE_JSON\" TEXT," + // 22: visible_json
                "\"PIC_IDS_JSON\" TEXT," + // 23: pic_ids_json
                "\"CREATE_TIME\" INTEGER);"); // 24: create_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_WEIBO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserWeibo entity) {
        stmt.clearBindings();
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(1, user_id);
        }
 
        String created_at = entity.getCreated_at();
        if (created_at != null) {
            stmt.bindString(2, created_at);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(3, id);
        }
 
        Long mid = entity.getMid();
        if (mid != null) {
            stmt.bindLong(4, mid);
        }
 
        String idstr = entity.getIdstr();
        if (idstr != null) {
            stmt.bindString(5, idstr);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(6, text);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(7, source);
        }
 
        Boolean favorited = entity.getFavorited();
        if (favorited != null) {
            stmt.bindLong(8, favorited ? 1L: 0L);
        }
 
        Boolean truncated = entity.getTruncated();
        if (truncated != null) {
            stmt.bindLong(9, truncated ? 1L: 0L);
        }
 
        String in_reply_to_status_id = entity.getIn_reply_to_status_id();
        if (in_reply_to_status_id != null) {
            stmt.bindString(10, in_reply_to_status_id);
        }
 
        String in_reply_to_user_id = entity.getIn_reply_to_user_id();
        if (in_reply_to_user_id != null) {
            stmt.bindString(11, in_reply_to_user_id);
        }
 
        String in_reply_to_screen_name = entity.getIn_reply_to_screen_name();
        if (in_reply_to_screen_name != null) {
            stmt.bindString(12, in_reply_to_screen_name);
        }
 
        String thumbnail_pic = entity.getThumbnail_pic();
        if (thumbnail_pic != null) {
            stmt.bindString(13, thumbnail_pic);
        }
 
        String bmiddle_pic = entity.getBmiddle_pic();
        if (bmiddle_pic != null) {
            stmt.bindString(14, bmiddle_pic);
        }
 
        String original_pic = entity.getOriginal_pic();
        if (original_pic != null) {
            stmt.bindString(15, original_pic);
        }
 
        String geo_json = entity.getGeo_json();
        if (geo_json != null) {
            stmt.bindString(16, geo_json);
        }
 
        String user_json = entity.getUser_json();
        if (user_json != null) {
            stmt.bindString(17, user_json);
        }
 
        String retweeted_status_json = entity.getRetweeted_status_json();
        if (retweeted_status_json != null) {
            stmt.bindString(18, retweeted_status_json);
        }
 
        Integer reposts_count = entity.getReposts_count();
        if (reposts_count != null) {
            stmt.bindLong(19, reposts_count);
        }
 
        Integer comments_count = entity.getComments_count();
        if (comments_count != null) {
            stmt.bindLong(20, comments_count);
        }
 
        Integer attitudes_count = entity.getAttitudes_count();
        if (attitudes_count != null) {
            stmt.bindLong(21, attitudes_count);
        }
 
        Integer mlevel = entity.getMlevel();
        if (mlevel != null) {
            stmt.bindLong(22, mlevel);
        }
 
        String visible_json = entity.getVisible_json();
        if (visible_json != null) {
            stmt.bindString(23, visible_json);
        }
 
        String pic_ids_json = entity.getPic_ids_json();
        if (pic_ids_json != null) {
            stmt.bindString(24, pic_ids_json);
        }
 
        Long create_time = entity.getCreate_time();
        if (create_time != null) {
            stmt.bindLong(25, create_time);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2);
    }    

    /** @inheritdoc */
    @Override
    public UserWeibo readEntity(Cursor cursor, int offset) {
        UserWeibo entity = new UserWeibo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // user_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // created_at
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // id
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // mid
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // idstr
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // text
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // source
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // favorited
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // truncated
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // in_reply_to_status_id
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // in_reply_to_user_id
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // in_reply_to_screen_name
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // thumbnail_pic
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // bmiddle_pic
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // original_pic
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // geo_json
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // user_json
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // retweeted_status_json
            cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18), // reposts_count
            cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19), // comments_count
            cursor.isNull(offset + 20) ? null : cursor.getInt(offset + 20), // attitudes_count
            cursor.isNull(offset + 21) ? null : cursor.getInt(offset + 21), // mlevel
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // visible_json
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // pic_ids_json
            cursor.isNull(offset + 24) ? null : cursor.getLong(offset + 24) // create_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserWeibo entity, int offset) {
        entity.setUser_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCreated_at(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setMid(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIdstr(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setText(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSource(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setFavorited(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setTruncated(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setIn_reply_to_status_id(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setIn_reply_to_user_id(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setIn_reply_to_screen_name(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setThumbnail_pic(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBmiddle_pic(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setOriginal_pic(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setGeo_json(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setUser_json(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setRetweeted_status_json(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setReposts_count(cursor.isNull(offset + 18) ? null : cursor.getInt(offset + 18));
        entity.setComments_count(cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19));
        entity.setAttitudes_count(cursor.isNull(offset + 20) ? null : cursor.getInt(offset + 20));
        entity.setMlevel(cursor.isNull(offset + 21) ? null : cursor.getInt(offset + 21));
        entity.setVisible_json(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setPic_ids_json(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setCreate_time(cursor.isNull(offset + 24) ? null : cursor.getLong(offset + 24));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UserWeibo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UserWeibo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
